dist: xenial
addons:
  apt:
    packages:
      - build-essential
      - curl
      - libltdl7
      - git
      - make

services:
  - docker

language: python
python:
  - "3.7"

before_install:
  - docker-compose up node compiler

install:
  - pip install -r requirements.txt

script: make test