branches:
  only:
  - master
  - develop
  - upcoming

dist: xenial
addons:
  apt:
    packages:
      - build-essential
      - curl
      - libltdl7
      - git
      - make

services:
  - docker

language: python
python:
  - "3.7"

env:
  global:
    - TEST_NODE=http://localhost:3013
    - TEST_URL=http://localhost:3013
    - TEST_DEBUG_URL=http://localhost:3113
    - TEST_NETWORK_ID=ae_devnet
    - COMPILER_URL=http://localhost:3080

cache:
  timeout: 604800 # 7 days
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

before_install:
  - docker-compose up -d node compiler

install:
  - pip install -r requirements.txt

jobs:
  include:
    - if: branch = upcoming
        env:
          - COMPILER_TAG=latest
          - NODE_TAG=master
    - stage: Tests
      name: Test AENS, Channels
      script:
        - make lint
        - make test TEST_OPTS="-k 'test_name or test_channel'"
    - stage: Tests
      name: Test Compiler, Contracts, Sophia Transformation, Hashing, CLI, HDWallet, Oracle, Node, OpenAPI, Signing, Transactions, Utils
      script:
        - make lint
        - make test TEST_OPTS="-k 'test_sophia or test_contract_native or test_type_conversion_to_sophia or test_oracle or test_cli or test_transaction or test_utils or test_hashing or test_hdwallet or test_node or test_generatedcli or test_signing'"
    - stage: Tests
      name: Test API, Tutorials, Examples
      script:
        - make lint
        - make test TEST_OPTS="-k 'test_api or test_tutorial or test_example'"