# Heads-Up: This Dockerfile is *exclusively* used for CI. It is referenced by
# Jenkinsfile and should not be used by any other means.

FROM python:3-slim

USER root

RUN apt-get update && apt-get -y install build-essential curl libltdl7 git make \
	&& pip install poetry \
  && poetry install

WORKDIR /app

RUN curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose