from aeternity.hdwallet import HDWallet

def test_tutorial_hdwallet():

    # Generating a mnemonic
    mnemonic = HDWallet.generate_mnemonic()

    assert mnemonic is not None

    # Initializing the HDWallet
    # (if mnemonic is not provided, a one will be autogenerated during initialization)
    hdwallet = HDWallet(mnemonic)

    assert hdwallet.master_key is not None

    # Derive child accounts
    # if you want to derive a child key with an specific account and/or address index
    # then you can pass them to the method
    # By default, every time you generate a child key, the account index is auto generated
    key_path, account = hdwallet.derive_child()

    assert key_path is not None and account is not None