peers: []

http:
  external:
    port: 3013
  internal:
    listen_address: 0.0.0.0

websocket:
  channel:
    listen_address: 0.0.0.0

keys:
  peer_password: "top secret"
  dir: ./keys

chain:
  persist: true

mining:
  autostart: true
  beneficiary: "ak_25MZX3BXYP32YDPGWsJqYZ6CgWnqD93VdpCYaTk6KsThEbeFJX"
  cuckoo:
    miner:
      executable: mean15-generic
      extra_args: ""
      node_bits: 15

fork_management:
  network_id: "ae_devnet"
